### ISSUE TITLE
(Auto) sort cards

### ISSUE THREAD

**Issue by Al2Klimov** [Al2Klimov/icingaweb2-module-fourcolors#11]

**Comment by theFeu** [comment]
I feel like everyone sorts their cards differently, and sorting them manually would be the only option to satisfy the people who care enough about sorting cards to ask for this feature.

**Comment by Al2Klimov** [comment]
Can be implemented if auto-sort explicitly doesn't suffice.

**Comment by theFeu** [comment]
I would not give it the highest priority :)

**Comment by Al2Klimov** [comment]
# To do

* [ ] #6
