### ISSUE TITLE
Indicate if it's the user's turn more prominently

### ISSUE THREAD

**Issue by Al2Klimov** [Al2Klimov/icingaweb2-module-fourcolors#12]

**Comment by Al2Klimov** [comment]
@theFeu Do you think a modal with the action form would help?

**Comment by theFeu** [comment]
I think a "Toast" popup would be the best solution.
We want to keep the amount of times a user has to click at a minimum :)

**Comment by theFeu** [comment]
Playing a sound would probably be helpful too (in case you are not looking at the window), but I don't know that would be something we want.

**Comment by Al2Klimov** [comment]
1. "Toast" popups need permission AFAIK
2. Modals wouldn't differ from current

**Comment by theFeu** [comment]
I remember that Icinga Web used to have a toast funcitionality you could use - that was a few years back, so I am not sure if it still exists or if it was replaced by the modal.

**Comment by Al2Klimov** [comment]
Do you mean the bottom bar saying like "Rescheduling 1337 checks..."?

**Comment by theFeu** [comment]
I don't know that one 🙃 
It's a banner popping up from the bottom of the screen, usually in a bright colour to catch the eye?

**Comment by Al2Klimov** [comment]
A _bar_, but yes.

**Comment by theFeu** [comment]
We are probably talking about the same thing then.
I think it would suffice to catch the eye (+ maybe a fun sound)

Especially, since the toast is less invasive than a modal, that you have to click / buttonpress away, and thus hindering the game flow :)

**Comment by Al2Klimov** [comment]
If it suffices and is less invasive than a modal, I'll take the modal. :)

**Comment by Al2Klimov** [comment]
## To do

* [ ] #10
