### ISSUE TITLE
There should be a players turn marker in the list

### ISSUE THREAD

**Issue by theFeu** [Al2Klimov/icingaweb2-module-fourcolors#5]
If we have multiple players, I think there should be a way of telling whos turn it is at the moment.
This helps to keep the game going, if someone doesn't pay attention.
Happens all the time in a tabletop setting as well.

**Comment by Al2Klimov** [comment]
FYI it's the 1st user in the table. But yes...

**Comment by Al2Klimov** [comment]
UX? Which UX? :P
